export const createDefaultItem = (slotIndex) => ({
  id: `item_${slotIndex}`,
  material: 'STONE',
  slot: slotIndex,
  slots: [],
  display_name: '',
  lore: [],
  amount: 1,
  damage: 0,
  priority: 0,
  unbreakable: false,
  update: false,
  rgb: '',
  item_flags: [],
  enchantments: [],
  potion_effects: [],
  banner_meta: [],
  base_color: '',
  light_level: null,
  trim_material: '',
  trim_pattern: '',
  nbt_string: '',
  nbt_strings: [],
  nbt_int: '',
  nbt_ints: [],
  nbt_byte: '',
  nbt_bytes: [],
  hide_tooltip: false,
  enchantment_glint_override: false,
  rarity: '',
  model_data: null,
  model_data_component: null, // will hold { strings: [], floats: [], flags: [], colors: [] } when active
  item_model: '',
  tooltip_style: '',
  view_requirement: null,
  click_commands: [],
  left_click_commands: [],
  right_click_commands: [],
  middle_click_commands: [],
  shift_left_click_commands: [],
  shift_right_click_commands: [],
  click_requirement: null,
  left_click_requirement: null,
  right_click_requirement: null,
  shift_left_click_requirement: null,
  shift_right_click_requirement: null,
});

export const INITIAL_MENU_STATE = {
  menuName: 'my_menu',
  menu_title: '&8My Menu',
  open_command: 'mymenu',
  size: 27, // 9, 18, 27, 36, 45, 54
  inventory_type: 'CHEST',
  update_interval: 20,
  open_requirement: null,
  open_commands: [],
  items: {}, // key: slotIndex (0-53), value: ItemObject
};
