export const ACTION_TYPES = [
  { prefix: "[player]", label: "Player Command", description: "Executes a command on behalf of the clicking player." },
  { prefix: "[console]", label: "Console Command", description: "Executes a command from the server console." },
  { prefix: "[op]", label: "OP Command", description: "Executes a command as an OP player temporarily." },
  { prefix: "[message]", label: "Player Message", description: "Sends a chat message specifically to the player." },
  { prefix: "[broadcast]", label: "Broadcast Message", description: "Broadcasts a message to the entire server." },
  { prefix: "[minibroadcast]", label: "MiniMessage Broadcast", description: "Sends a MiniMessage formatted broadcast." },
  { prefix: "[openguimenu]", label: "Open GUI Menu", description: "Opens another DeluxeMenus configuration GUI by name." },
  { prefix: "[connect]", label: "Bungee Connect", description: "Connects the player to a BungeeCord server." },
  { prefix: "[close]", label: "Close Menu", description: "Closes the current menu immediately." },
  { prefix: "[refresh]", label: "Refresh Menu", description: "Refreshes the placeholders and item display states." },
  { prefix: "[chat]", label: "Chat Message", description: "Forces the player to send a chat message." },
  { prefix: "[sound]", label: "Play Sound", description: "Plays a sound effect to the player (e.g. ENTITY_PLAYER_LEVELUP)." },
  { prefix: "[playsound]", label: "Playsound Command", description: "Executes playsound command compatibility." },
  { prefix: "[worldsound]", label: "Play World Sound", description: "Plays sound at player's specific location." },
  { prefix: "[commandevent]", label: "Trigger CommandEvent", description: "Triggers a custom command event." },
  { prefix: "[takemoney]", label: "Take Economy Money", description: "Deducts a specific balance using Vault." },
  { prefix: "[givemoney]", label: "Give Economy Money", description: "Rewards a specific balance using Vault." },
  { prefix: "[givepermission]", label: "Give Permission", description: "Grants a LuckPerms permission node." },
  { prefix: "[takepermission]", label: "Remove Permission", description: "Removes a LuckPerms permission node." },
  { prefix: "[delay]", label: "Action Delay (Ticks)", description: "Pauses action pipeline execution for ticks (20 ticks = 1s)." },
  { prefix: "[json]", label: "JSON Message", description: "Sends a raw JSON text format component to the player." },
  { prefix: "[jsonbroadcast]", label: "JSON Broadcast", description: "Broadcasts raw JSON text components server-wide." },
  { prefix: "[placeholder_api_parse]", label: "PAPI Parse Check", description: "Checks or parses a placeholder string." }
];
