export const ENCHANTMENTS = [
  { id: "protection", label: "Protection" },
  { id: "fire_protection", label: "Fire Protection" },
  { id: "feather_falling", label: "Feather Falling" },
  { id: "blast_protection", label: "Blast Protection" },
  { id: "projectile_protection", label: "Projectile Protection" },
  { id: "respiration", label: "Respiration" },
  { id: "aqua_affinity", label: "Aqua Affinity" },
  { id: "thorns", label: "Thorns" },
  { id: "depth_strider", label: "Depth Strider" },
  { id: "frost_walker", label: "Frost Walker" },
  { id: "soul_speed", label: "Soul Speed" },
  { id: "swift_sneak", label: "Swift Sneak" },
  { id: "sharpness", label: "Sharpness" },
  { id: "smite", label: "Smite" },
  { id: "bane_of_arthropods", label: "Bane of Arthropods" },
  { id: "knockback", label: "Knockback" },
  { id: "fire_aspect", label: "Fire Aspect" },
  { id: "looting", label: "Looting" },
  { id: "sweeping_edge", label: "Sweeping Edge" },
  { id: "efficiency", label: "Efficiency" },
  { id: "silk_touch", label: "Silk Touch" },
  { id: "unbreaking", label: "Unbreaking" },
  { id: "fortune", label: "Fortune" },
  { id: "power", label: "Power" },
  { id: "punch", label: "Punch" },
  { id: "flame", label: "Flame" },
  { id: "infinity", label: "Infinity" },
  { id: "luck_of_the_sea", label: "Luck of the Sea" },
  { id: "lure", label: "Lure" },
  { id: "loyalty", label: "Loyalty" },
  { id: "impaling", label: "Impaling" },
  { id: "riptide", label: "Riptide" },
  { id: "channeling", label: "Channeling" },
  { id: "multishot", label: "Multishot" },
  { id: "piercing", label: "Piercing" },
  { id: "quick_charge", label: "Quick Charge" },
  { id: "mending", label: "Mending" },
  { id: "vanishing_curse", label: "Curse of Vanishing" },
  { id: "binding_curse", label: "Curse of Binding" }
];
